config/routes.rb
Rails.application.routes.draw do

  get 'pages/show'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    resources :festivals, only: [:show, :index] do
    end
    resources :events, only: [:show, :index] do
    end
    resources :shows, only: [:show, :index] do
    end
    resources :artists, only: [:show, :index] do
    end
    resources :venues, only: [:show, :index] do
    end
    resources :pages, only: [:show] do
    end
    resources :news, only: [:show, :index] do
    end
    resources :videos, only: [:show, :index] do
    end
    resources :galleries, only: [:show, :index] do
    end
    resources :sponsors, only: [:index] do
    end
    resources :newsletters, only: [:new, :create]
    resources :contacts, only: [:new, :create]
    resources :press_contacts, only: [:new, :create]

  end

  devise_for :festivals, ActiveAdmin::Devise.config.merge({path: '/admin'})
  devise_for :admin_users, ActiveAdmin::Devise.config.merge({path: '/super_admin'})
  ActiveAdmin.routes(self)
  
  root to: "festivals#lookup"
  get '/:locale' => 'festivals#lookup'

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

end

app/models/festival.rb
class Festival < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  active_admin_translates :menu_title_home, :menu_title_artists, :menu_title_events, :menu_title_news, :menu_title_videos, :menu_title_venues, :menu_title_contacts, :menu_title_sponsors, :menu_title_press, :menu_title_galleries

  has_many :artists, :dependent => :destroy
  has_many :days, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :venues, :dependent => :destroy
  has_many :presentations, :dependent => :destroy
  has_many :news, :dependent => :destroy
  has_many :sponsors, :dependent => :destroy
  has_many :videos, :dependent => :destroy
  has_many :templates, :dependent => :destroy
  has_many :widgets, :dependent => :destroy
  has_many :newsletters, :dependent => :destroy
  has_many :splashes, :dependent => :destroy
  has_many :stages, :dependent => :destroy
  has_many :galleries, :dependent => :destroy
  has_many :pages, :dependent => :destroy

  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true

  has_attached_file :logo, :styles => { :thumb => "120x80>", :small => '480x320>', :medium => '720x480>', :large => '1080x720>' },
            :url  => "/assets/logos/:id/:style/:basename.:extension",
            :path => ":rails_root/public/assets/logos/:id/:style/:basename.:extension"
            
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  has_attached_file :image, :styles => { :thumb => "120x80>", :small => '480x320>', :medium => '720x480>', :large => '1080x720>' },
            :url  => "/assets/festivals/:id/:style/:basename.:extension",
            :path => ":rails_root/public/assets/festivals/:id/:style/:basename.:extension"

  has_attached_file :css_file, :url => "/assets/styles/:id/:basename.:extension", :path => ":rails_root/public/assets/styles/:id/:basename.:extension"
 
  validates_attachment :css_file, :content_type => { :content_type => "text/css" }
   
  extend FriendlyId
	friendly_id :name, use: :slugged

	def slug_candidates
    [
      :name,
      [:name, :id]
    ]
  end
end

app/controllers/festivals_controller.rb
class FestivalsController < ApplicationController
  
  def festival_id
  	params[:id]
  end

  def show
  	@festival = Festival.find_by_url(request.domain(10).gsub(/^www./,""))
    @videos = @festival.videos.where(featured: 'yes')
    @news = @festival.news.last(3).reverse

    set_meta_tags(
      title: @festival.name,
      description: @festival.description,
      keywords: @festival.keywords,
      og: {
        title: @festival.name,
        type:'website',
        url: @festival.url,
        image: @festival.image.url(:large),
        description: @festival.description
      }
    )
    if @festival.published?
      render "festivals/#{@festival.slug}/festival/show", :layout => @festival.slug
    else
      render "festivals/#{@festival.slug}/festival/soon"
    end
  end

  def lookup
    if festival = Festival.find_by_url(request.domain(10).gsub(/^www./,"")) || Festival.find(1)
      params[:id] = festival.id
      show
    else
      render text: 'this is my landing wohoo'
    end
  end
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/views/festivals/off-at-forum/festival/show.html.haml
- title "#{@festival.name}"

.wrapper
  %ul#scene.scene{"data-calibrate-y" => "false"}
    %li.layer.layer1{"data-depth" => "0.05"}
    %li.layer.layer2{"data-depth" => "0.02"}
    %li.layer.layer3{"data-depth" => "0.10"}
    %li.layer.layer4{"data-depth" => "0.00"}
    %li.layer.layer5{"data-depth" => "0.00"}
#home.section
  .intro
    .bottom
      - @festival.splashes.each do |splash|
        .row
          .col-md-4
            %p= simple_format(splash.title)
          .col-md-4
            = link_to splash.call_to_action, splash.call_to_action_link, class: 'btn btn-block btn-default btn-lg'
.artists.section.normalizer
  .left
    %p= @festival.menu_title_artists
  .container
    .row
      - @festival.events.each do |event|
        .col-sm-4.col-md-4.animate-box{"data-animate-effect" => "fadeInUp"}
          .row
            %h2
              = l(event.starts_on.to_date, format: '%B %d, %Y')
              %span= event.name

          - @presentations = event.presentations.group_by { |t| t.stage_id }
          - @presentations.sort.each do |stage, artists|
            .row
              %h3= Stage.find(stage).name
            - for artist in artists
              .row
                %h4 #{artist.time.strftime("%H:%M")} - #{artist.ends.strftime("%H:%M")}
              .row
                = link_to artist.name, artist_path(artist), class: 'artist'
          .row
            = link_to t('events.tickets'), events_path, class: 'btn btn-danger btn-sm'
.video.section
  .left
    %p= @festival.menu_title_videos
  .vcenter
    .container
      - @videos.each do |video|
        .row
          = link_to video.link, class: 'swipebox' do
            .col-md-8.col-md-offset-2.sixteen-nine.animate-box.text-center{"data-animate-effect" => "fadeInUp"}
              .image.cover{:style => "background-image: url(#{video.image.url(:medium)})"}
              %i.fa.fa-play
      .row
        .col-md-6.col-md-offset-3.text-center
          = link_to t('videos.view_all'), videos_path, class: 'btn btn-default btn-sm'
.news.section
  .left
    %p= @festival.menu_title_news
  .vcenter
    .container
      .row
        - @news.each do |news|
          .col-sm-12.col-md-4.animate-box.item{"data-animate-effect" => "fadeInUp"}
            .row
              %h2= l(news.date.to_date, format: '%B %d, %Y')
              %h3= news.title
            .row
              .col-md-10.sixteen-nine
                .image.cover{:style => "background-image: url(#{news.image.url(:medium)})"}
            .row
              .col-md-10
                .row
                  %p= truncate(news.body, :length => 140)
                  = link_to 'View More', news_path(news), class: 'btn btn-danger btn-sm'
      .row
        .col-md-6.col-md-offset-3.text-center
          = link_to t('news.all'), news_index_path, class: 'btn btn-default btn-sm'
.partners.section.text-center
  .left
    %p= @festival.menu_title_sponsors
  .vcenter
    .container
      .row
        - @festival.sponsors.each do |sponsor|
          = link_to sponsor.link, class: 'partner' do
            = image_tag sponsor.image.url(:small)
:javascript
  $(function(){
    $('#scene').parallax();
  });

app/views/festivals/off-at-forum/festival/soon.html.haml
.soon
  .vcenter
    %p.text-center
      COMING SOON...