config/routes.rb
Rails.application.routes.draw do

  get 'pages/show'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    resources :festivals, only: [:show, :index] do
    end
    resources :events, only: [:show, :index] do
    end
    resources :shows, only: [:show, :index] do
    end
    resources :artists, only: [:show, :index] do
    end
    resources :venues, only: [:show, :index] do
    end
    resources :pages, only: [:show] do
    end
    resources :news, only: [:show, :index] do
    end
    resources :videos, only: [:show, :index] do
    end
    resources :galleries, only: [:show, :index] do
    end
    resources :sponsors, only: [:index] do
    end
    resources :newsletters, only: [:new, :create]
    resources :contacts, only: [:new, :create]
    resources :press_contacts, only: [:new, :create]

  end

  devise_for :festivals, ActiveAdmin::Devise.config.merge({path: '/admin'})
  devise_for :admin_users, ActiveAdmin::Devise.config.merge({path: '/super_admin'})
  ActiveAdmin.routes(self)
  
  root to: "festivals#lookup"
  get '/:locale' => 'festivals#lookup'

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :festival
  belongs_to :day
  belongs_to :venue
  belongs_to :stage
  has_many :presentations

  active_admin_translates :description

  has_attached_file :image, :styles => { :thumb => "120x80>", :small => '480x320>', :medium => '720x480>', :large => '1080x720>', :high => '1920x1080>' },
            :url  => "/assets/events/:id/:style/:basename.:extension",
            :path => ":rails_root/public/assets/events/:id/:style/:basename.:extension"
            
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :event_artists, :dependent => :destroy
  has_many :artists, :through => :event_artists
	has_many :event_stages, :dependent => :destroy
	has_many :stages, :through => :event_stages

  accepts_nested_attributes_for :event_artists, :allow_destroy => true
  accepts_nested_attributes_for :event_stages, :allow_destroy => true

  extend FriendlyId
  friendly_id :slug_candidates, use: :history

  def slug_candidates
    [
        [:id, :name]
    ]
  end

    after_commit :update_slug, on: :create

  def update_slug
    unless slug.include? self.id.to_s
      self.slug = nil
      self.save
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  prepend_view_path Template.resolver
  
  def index
  	@festival = Festival.friendly.find(festival.id)

  	set_meta_tags(
      title: @festival.name, 
      description: @festival.description, 
      keywords: @festival.keywords, 
      og: { 
        title: @festival.name, 
        type:'website', 
        url: @festival.url, 
        image: @festival.image.url(:large), 
        description: @festival.description 
      }
    )
    render "festivals/#{@festival.slug}/events/index", :layout => @festival.slug

  end

  def show
  	@festival = Festival.friendly.find(festival.id)
  	@event = Event.friendly.find(params[:id])

  	set_meta_tags(
      title: @event.name, 
      description: @event.description, 
      keywords: @festival.keywords, 
      og: { 
        title: @event.name, 
        type:'website', 
        url: @festival.url, 
        image: @event.image.url(:large), 
        description: @event.description 
      }
    )
    render "festivals/#{@festival.slug}/events/show", :layout => @festival.slug

  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/festivals/proyectual/events/index.html.haml
%section#events.grid.bg-dark-grey
  .no-gutter.splashes
    .col-md-12.header.text-center
      .gradient2
      %h1.section-heading.vcenter
        = t('events.title')
  .container
    - @years.each do |year|
      .year
        .row
          .col-md-2.col-md-offset-5.hexagon.text-center
            %h2.section-heading #{year.name}
        .row
          .vert-line
        .row
          .no-gutter
            - year.events.each do |event|
              .col-xs-12.col-sm-12.col-md-12.grid-item
                - if event.images.empty?
                  .row.no-gutter
                    = link_to(event_path(event), class: 'col-sm-6 col-md-6 grid-link') do
                      .grid-hover
                        .grid-hover-content
                          .lines
                            .line.top
                            .line.right
                            .line.bottom
                            .line.left
                          %p= t('events.view_more') 
                      .ph.image-not-available
                    .col-sm-6.col-md-6.grid-caption.text-left
                      %h4
                        #{truncate(event.name, :length => 40)}
                      %p
                        #{truncate(event.description, :length => 240)}
                - else
                  - event.images.each do |image|
                    - if image.cover == true
                      .row.no-gutter
                        = link_to(event_path(event), class: 'col-sm-6 col-md-6 grid-link') do
                          .grid-hover
                            .grid-hover-content
                              .lines
                                .line.top
                                .line.right
                                .line.bottom
                                .line.left
                              %p= t('events.view_more') 
                          .ph{:style => "background-image: url(#{image.file.url(:medium)})"}
                        .col-sm-6.col-md-6.grid-caption.text-left
                          %h4
                            #{truncate(event.name, :length => 40)}
                          %p
                            #{truncate(event.description, :length => 240)}
        .row.hidden-xs
          .vert-line
    .row
      .col-md-2.col-md-offset-5.text-center
        = link_to('', '#', class: 'gotop')

app/views/festivals/proyectual/events/show.html.haml
%section#events.grid.bg-grey
  .no-gutter.splashes
    .col-md-12.header.text-center
      .ph{:style => "background-image: url(#{@event.images.first.file.url(:large)})"}
      .gradient
      .vcenter
        %h1.section-heading= @event.name
        %ul.list-inline.social-buttons
          %li
            = link_to(@event.facebook) do
              %i.fa.fa-facebook
          %li
            = link_to(@event.instagram) do
              %i.fa.fa-instagram
          %li
            = link_to(@event.twitter) do
              %i.fa.fa-twitter
          %li
            = link_to(@event.youtube) do
              %i.fa.fa-youtube
  .container
    .row.subsection
      .col-md-2.col-md-offset-5.hexagon.text-center.neg-margin
        %h2.section-heading I
      .col-md-12
        %h2.section-heading.text-center= t('events.about_this_event')
    .row
      .col-md-10.col-md-offset-1
        .row
          .col-md-6.grid-item
            .section-body
              #{simple_format(@event.description)}
          .col-md-6.grid-item
            .row
              .col-md-12
                .section-body
                  %p= t('events.artists_who_played')
            .row
              .col-md-12
                .section-body
                  - @artists.each do |artist|
                    = link_to "#{artist}" do
                      #{artist.name}
    .row.subsection
      .col-md-2.col-md-offset-5.hexagon.text-center
        %h2.section-heading II
      .col-md-12
        %h2.section-heading.text-center= t('events.after_movie')
      .col-md-8.col-md-offset-2
        .video
          .video-cover{:style => "background-image: url(#{@event.video_cover.url(:large)})"}
          = link_to('', @event.video, class: 'swipebox-video video-play')
          
%section.bg-dark-grey.offset
  .container
    .row.subsection
      .col-md-2.col-md-offset-5.hexagon.text-center
        %h2.section-heading III
      .col-md-12
        %h2.section-heading.text-center= t('events.event_history')
    .row
      %ul.timeline
        - @events.each do |event|
          %li
            .timeline-image{:style => "background-image: url(#{@event.images.first.file.url(:large)})"}
              .hexagon-mask
            .timeline-panel
              .timeline-heading
                %h4
                  #{event.name}
              .timeline-body
                %p
                  #{event.description}

    .row.hidden-xs
      .vert-line
    .row
      .col-md-2.col-md-offset-5.text-center.margin
        = link_to('', '#', class: 'gotop')